FROM fedora:30

RUN dnf -y install \
  --setopt=deltarpm=0 \
  --setopt=install_weak_deps=false \
  --setopt=tsflags=nodocs \
  bash \
  nmap-ncat \
  python3-devel \
  # Install RPM dependencies from estuary-api otherwise they'll be installed via pip which won't map
  # to production
  python3-fedmsg \
  python3-flake8 \
  python3-flask \
  python3-koji \
  python3-mock \
  python3-neomodel \
  python3-pyOpenSSL \
  python3-pytest \
  python3-pytest-cov \
  python3-pytz \
  python3-requests \
  python3-requests-kerberos \
  python3-tox \
  python3-flake8-docstrings \
  && dnf clean all

VOLUME /src
WORKDIR /src
CMD ["bash", "docker/test.sh"]
